# Generated by Django 5.2.16 on 2026-07-21 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='aadhar_number_encrypted',
            field=models.TextField(blank=True, default=''),
        ),
    ]
